title: Neil Bekker
logo: /assets/Neil_Bekker_pp.jpg
description: National Distribution Lead
email: pdbekkeruj@gmail.com
favicon: /assets/NBfavicon.ico
theme: jekyll-theme-minimal
sass:
  style: compressed
show_downloads: true

