title: Neil Bekker
theme: jekyll-theme-minimal
sass:
  style: compressed
logo: /assets/Neil_Bekker_pp.jpg
description: National Distribution Lead
favicon: /assets/NBfavicon.ico
show_downloads: true
email: pdbekkeruj@gmail.com  
